# yaml-language-server: $schema=
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'audit_ready_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'audit_ready_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  audit_ready_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +docs:
        node_color: "MediumSeaGreen"
      incremental:
        +docs:
          node_color: "#27AE60"
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: "Orange"
    marts:
      +materialized: table
      +docs:
        node_color: "RoyalBlue"
      finance:
        +schema: finance
    utilities:
      +materialized: table
      +docs:
        node_color: "#95A5A6"

vars:
  incremental_lookback_days: 1

seeds:
  audit_ready_dbt:
    +docs:
      node_color: "#8D6E63"

tests:
  audit_ready_dbt:
    +docs:
      node_color: "#E74C3C" 
